### ISSUE TITLE
What is difference between next_diag_inclusive and vim.diagnostic.get_next

### ISSUE THREAD

**Issue by nullchilly** [andrewferrier/textobj-diagnostic.nvim#7]
Here is the code side by side

https://github.com/andrewferrier/textobj-diagnostic.nvim/blob/main/lua/textobj-diagnostic.lua#L21_L57

https://github.com/neovim/neovim/blob/master/runtime/lua/vim/diagnostic.lua#L497_544

**Comment by andrewferrier** [comment]
I've answered that by way of a table in the README: https://github.com/andrewferrier/textobj-diagnostic.nvim#mappings. Please let me know if it's not clear.

**Comment by nullchilly** [comment]
Uh can't you just change the cursor position?

```lua
local cursor = vim.api.nvim_win_get_cursor(0)
cursor[2] = cursor[2] - 1
vim.pretty_print(vim.diagnostic.get_next({ cursor_position = cursor }))
```

**Comment by andrewferrier** [comment]
Interesting idea, thanks! I'll test this out later, just want to figure out how it will behave on some corner cases.

**Comment by nullchilly** [comment]
@andrewferrier Oh yeah I accidentally decrease the column instead of the row

It should be `cursor[1] = cursor[1] - 1`

**Comment by andrewferrier** [comment]
Yeah, thanks for this. Unfortunately, this still doesn't work. I think using `get_next()` is fundamentally not going to work here, as it doesn't account for the fact that the diagnostic has *width* - since it is exclusive, it doesn't have to look at anything beyond the first characters - whereas `next_diag_inclusive()` is doing that.

**Comment by nullchilly** [comment]
@andrewferrier Yeah I agree

Two more suggestions though:
- Add [.stylua.toml](https://github.com/JohnnyMorganz/StyLua)
- Remove the `demos/` directory and upload the image to github instead. In this case it's fine since there's only one gif but if you plan to add more it's unnecessary heavy to clone.

**Comment by andrewferrier** [comment]
Thanks. `.stylua.toml` now added.

When you mention the `demos/` directory, I agree, but where on GitHub are you suggesting I should upload it? As far as I know, there is no general file storage beyond that provided for repos.

**Comment by nullchilly** [comment]
@andrewferrier You click edit `README.md` on github, drag and drop the gif into it.
